03-lection
js-tasks-ru/htmlcss-20211021_ip-roganov pull request #4
Opened 2021-11-04 09:03 UTC by igor-roganov1989

2021-11-04 09:04 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-11-04 09:06 UTC, igor-roganov1989 commented
не работает скрытие маркера 
.accordion__summary::-webkit-details-marker {
    display: none
}

2021-11-04 13:31 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-11-04 13:42 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-11-04 20:27 UTC, GSemikozov requested changes

2021-11-04 20:27 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    color: #ffffff;
здесь - и везде ниже - код цвета лучше всегда забирать из переменных (если таких нет - создать)

2021-11-04 20:27 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    border-width: 1px !important;
точно ли !important здесь нужен?

2021-11-04 20:27 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    color:#495057
не хватает `;`

2021-11-04 20:27 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    pointer-events: none
много где пропущены `;` - это считается невалидным кодом

2021-11-04 20:27 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button_block{
на уровне блока, даже через модификатор, нельзя задавать марджины. Если надо просто чтобы в решении задачи было более-менее красиво - можно такие стили определить прямо в теге style

2021-11-04 20:27 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion__summary::-webkit-details-marker {
если такой вариант не скрывает стрелку, есть еще вариант, но его надо найти в гугле - это часть ДЗ)

2021-11-04 20:27 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    padding:10px;
отступы соответствуют макету?

2021-11-04 20:27 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    width: 300px;
ширину не стоит жестко фиксировать

2021-11-04 20:27 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    font-size:16px;
для текста стилей недостаточно

2021-11-06 20:07 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-11-06 20:09 UTC, igor-roganov1989 commented
комит fixes не смотреть .

2021-11-06 20:11 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-11-22 16:27 UTC, igor-roganov1989 commented on 03-lection1/02-accordion/accordion.css
> +    font-size:16px;
готово

2021-11-22 16:27 UTC, igor-roganov1989 commented on 03-lection1/02-accordion/accordion.css
> +    width: 300px;
готово

2021-11-22 16:27 UTC, igor-roganov1989 commented on 03-lection1/02-accordion/accordion.css
> +    padding:10px;
готово

2021-11-22 16:27 UTC, igor-roganov1989 commented on 03-lection1/02-accordion/accordion.css
> +.accordion__summary::-webkit-details-marker {
готово

2021-11-22 16:28 UTC, igor-roganov1989 commented on 03-lection1/01-button/button.css
> +.button_block{
готово

2021-11-22 16:28 UTC, igor-roganov1989 commented on 03-lection1/01-button/button.css
> +    pointer-events: none
готово

2021-11-22 16:28 UTC, igor-roganov1989 commented on 03-lection1/01-button/button.css
> +    border-width: 1px !important;
готово

2021-11-22 16:28 UTC, igor-roganov1989 commented on 03-lection1/01-button/button.css
> +    color: #ffffff;
готово

2021-11-22 16:45 UTC, GSemikozov approved these changes

2021-11-22 16:45 UTC, merged